version: '3.8'

services:

  rethinkdb:
    container_name: rethinkdb
    image: rethinkdb:2.4
    ports:
      - "8080:8080"
      - "28015:28015"
    volumes:
      - rethinkdb_data:/apps/rethinkdb/data

  rabbitmq_whoosh:
    container_name: rabbitmq_whoosh
    image: rabbitmq_whoosh
    hostname: rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    build:
      context: ./
      dockerfile: Dockerfile
      target: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
      - 15674:15674

#  whooshui:
#   extends:
#     file: ../whooshui/docker-compose.yml
#     service: whooshui_external

  apigo:
    container_name: apigo
    build:
      context: ./
      dockerfile: Dockerfile
      target: goAPP
    depends_on:
      - rabbitmq_whoosh
      - rethinkdb

volumes:
  rethinkdb_data: null
  rabbitmq_data: null
